const mongoose = require('mongoose'); //require mongoose package
mongoose.Promise = global.Promise; // setting the built in(ES6) mongoose Promise to be global
const slug = require('slugs');

const storeSchema = new mongoose.Schema({
  name: {
    type: String,
    trim: true,
    required: 'Please enter a store name!'
  },
  slug: String, // autogenerated
  description: {
    type: String,
    trim: true
  },
  tags: [String]
});

//this function gets called whenever you modify the store name
storeSchema.pre('save', function(next) {
  if(!this.isModified('name')) {
    next(); //skip it
    return; //stop this function from running
  }
  this.slug = slug(this.name);
  next();
})

module.exports = mongoose.model('Store', storeSchema);
